\clearpage

# Conclusion

The Industrial Revolution, the Assembly Line, the mechanization of agriculture, robots on factory floors--these are all technological innovations that forced a realignment of labor. In each of these instances, laborers had to adapt to the situation, whether it was from learning a new skill or finding a new job. These innovations all led to leaps in global productivity, shaping the world as we now it today. The AI transition seems to be the next great technological innovation, one that will also force a realignment of labor. Unlike those noted previously, this innovation seems that it will affect higher skilled/wages more than unskilled labor. But, like all the others, capital is key and the gains seem like they will accrue to those with the means to procure the innovation.

Given the potential for AI to affect many aspects of the global economy, there has been a lot of recent media attention and research. However, it is clear that it is difficult to forecast labor interactions with, as well as the understanding potential productivity gains. In our work, we simulate the case where AI replaces human, clerical labor without improving productivity of labor. We show with the assumption that AI is internationally traded (i.e., it has a global price) it is likely that only the most developed countries with higher initial wages would invest in AI to replace clerical labor. 

We also show that the impact of such an adoption is likely to impact the welfare of the adopting countries by a large amount; however the sign of the welfare impact largely depends on the response of the clerical labor to the new market conditions: if the displaced clerical labor exits the market, AI adoption would result in an overall welfare loss. However, if clerical labor stays in the market and accepts lower wages, AI would boost the supply of labor and, in turn, adopting countries' welfare.

Finally, we consider the implication of taxing computing services when used in the form of AI to replace labor. We observe that a tax close to 100 percent would be required to make the adoption of AI infeasible. However, the impact of a smaller tax would depend on the response of the displaced clerical workers---in the world where clerical workers exit the labor market, a tax of over 50 percent would be required to make a substantial impact of reducing the negative welfare implications of AI adoption.

As mentioned above, there are many aspects of AI that are still unknown, and can change in the future. Our work operatlizes AI within a common CGE, future work could also consider the productivity interaction, or consider AI being introduced to developing countries at a lower rate than that for developed countries. 