# Introduction

Technological advancements provide consumers with innovative products and help fuel economic growth. Further, modern economic growth theory argues that the structural transformation from an agriculture-labor intensive society to manufacturing and finally services is predicated on the ability for technological progress in a given country. The rapid rise of Artificial Intelligence (AI) is positioned to be the next great technological advance, structurally altering production, much in the same way the Industrial Revolution changed manufacturing. But, like the Industrial Revolution, there will be winners and losers across sectors and countries, and the promise of adjustments to the labor force. In this work, we use a computable general equilibrium (CGE) model to determine what countries and what sectors gain and lose from the AI revolution.

Economists have linked changes in structural transformation–the movement of resources from agriculture to manufacturing and finally services-to economic growth since the end of the Depression [see e.g., @clark1940; @fisher1939; @kuznets1966]. In more recent work, @anderson2023 state that the share of employment in agriculture will inevitably decline in the course of economic growth, followed by declines in employment in manufacturing. This happens as agriculture becomes more capital-intensive and rising wage rates in manufacturing encourage the use of automation. Usually, it is developed countries that can afford this technology. Developed countries also tend to have more productivity in agriculture (which is again, a result of more capital-intensive use); although the work by @gangopadhyay2021 claims that improved agricultural productivity may keep labor in agriculture and also draw labor away from manufacturing.[^1] What is clear is that countries that have less employment in agriculture and manufacturing tend to be the wealthiest countries. Appendix 1 presents data on the share of labor in each sector and GDP per capita, the correlation for the share of labor in agriculture and GDP per capita is -0.59 and the share for manufacturing is -0.13. The share for the share of labor in services and GDP per capita is 0.65.

[^1]: We largely disagree with their claim as labor in agriculture in the United States (they use data for the U.S. from 1820-2017) has been falling and productivity still increases. We think that the phenomena they describe could happen in developing countries that depend less on capital.

Much like the structural transformation from agriculture to services that has taken place in developed countries, AI is capital-intensive with the changes to the economy filtering through changes in labor. Despite being a relative new research topic, there has been work aimed at trying to understand the potential labor effect, as well as potential macroeconomic impacts. In terms of labor, a primary concern has been potential jobs losses or decreases in wages. @irwin presents data showing that corporate profits have outpaced wage increases since computers began being used heavily, and so far, the AI boom has accumulated to capital, not workers. But, previous work examining the effect of automation on employment suggests that technological advancements might have a positive effect on employment. @fang2024 use panel data from 63 countries from 2005-2021 to show that a 1 percent increase in new industrial robot installations reduced the unemployment rate by 0.037-0.039 percent. @acemoglu find that firms who adopt robots have positive effects on hours worked in the Netherlands for 2009-2020. @autor2025 find that automation affects sectors differently, with wages and employment moving in opposite directions based on the skill level of the employee.

But, AI could be different than the advent of robots and automation. @weinstock note that productivity gains from previous technological innovations have largely accrued to high-income, skilled workers, but it is not clear if AI will have a similar effect. One reason for the lack of clarity around the labor impacts of AI is because many more occupations are exposed to AI, especially in developed countries that depend on service based industries (@unctad2025). One reason for the discussion of AI primarily in developed countries is because of the large energy demands from data centers (@mills2025). Even though the growth of AI is still occurring, there has been some work on the potential economic impacts. Results from @acemoglu2025 indicate that AI could widen the gap between capital and labor income [as noted in @irwin]. He also calculates that 20 percent of U.S. labor tasks are exposed to AI. @hampole2025 estimate that jobs with higher AI exposure (which tended to be higher-wage jobs) from 2010 to 2023 experienced a reduction in labor demand. However, they conclude that productivity enhancements and hiring by AI using firms offsets the lose in labor demand for those tasks that AI replaces.

What is clear from the emerging research is that AI will have some effect on labor markets, but the effects could vary. To contribute to this work, we use a CGE model to estimate the potential economic effects by country and by sector. There has been some general equilibrium (GE) research on AI, our work operationalizes AI within the Global Trade Analysis Project (GTAP), a global economic model widely used by policy makers. Using this computable version of a GE model allows for more global and inter-industry linkages.