# Scenario

We are interested in exploring the implications of allowing AI, a service generated by the information industry, to replace labor at various costs, for different industries and for different regions. Specifically, we focus on clerical labor which is the GTAP labor type that is most likely to be replaced by AI in all industries.[^1]

[^1]: @manning2026 note that clerical and administrative roles are most at risk. They are both considered clerical in GTAP.


We calibrate our model by setting the domestic price of AI and labor to one in the country with the highest clerical wages (the United States); we then set the relative wages of clerical labor in other regions to equal the relative total clerk wages per capita of each country/region. Furthermore, we assume $\psi=1$, i.e., one unit of labor can be substituted by one unit of AI [@eq-labor-combination]. For the relative wages assumed in the scenarios see @tbl-wages.

Much like our building of the model, other AI papers have had to make similar assumptions. Focusing on @acemoglu2025, he assumes that 19.9 percent of U.S. labor tasks are exposed to AI, 23 percent of computer tasks can be profitably performed by AI, and the average labor cost savings to be 27 percent–which, together, imply an average cost savings of 15.4 percent. One thing not mentioned in his work is the potential costs coming from AI, such as energy needs. Given that our AI sector comes with costs to produce AI (as given in input-output models), we are able to account for the costs and the benefits of AI.

Because of a wide range of clerical wages across the world and a global price for tradeable AI, it is likely that adoption of AI may vary across countries. As we explain earlier, we introduce a different production function for clerical labor that allows the combination of human labor and AI. However, changing production is likely to be costly; to account for this in our model, we assume that if a country or a region's use of AI falls below a small threshold (1 percent of total labor), then the country would not adopt AI at all.

We consider two main scenarios in this paper that differ in their assumptions on the supply of clerical labor: in the "no unemployment" scenario, we assume full employment, a standard assumption of the GTAP model, which results in wage adjustments. In the "unemployment" scenario, we assume that nominal wages remains fixed and, instead, clerical labor exits/enters the labor force to maintain this wage. Finally, for each scenario we implement a range of taxes on the use of AI by the industry in the range from 0 to 100 percent. 

```{=html}
<!-- ## Replacing professional staff with AI

In the second set of scenarios, we consider the replacement of technical staff with AI in the manufacturing and service sector. Again, we implement the adotpion of AI in three stages, first by each country alon, then by all developed countries and then, finally, by the entire world. We, again, test two different costs for AI implementation as in the scenarios mentioned above.

## Putting it all together

In the final set of scenarios we analyze the situation where both clerical labor in all industries and technical staff in manufacturing and services is replaced by AI at different costs by developed countries and the entire world.



 -->
```